version: "3.8"
services:
  db:
    image: postgres:15.5-alpine3.19
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql-static/data
      - pgsqlrun:/var/run/postgresql
    environment:
      POSTGRES_PASSWORD: 1234

volumes:
  pgdata:
    driver: local
  pgsqlrun:
    driver: local
